/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Aircraft = IDL.Record({
  'id' : IDL.Text,
  'registration' : IDL.Text,
});
export const Exercise = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const FlightLog = IDL.Record({
  'id' : IDL.Nat,
  'studentId' : IDL.Text,
  'exerciseId' : IDL.Text,
  'totalHours' : IDL.Float64,
  'date' : IDL.Text,
  'flightType' : IDL.Text,
  'instructorId' : IDL.Text,
  'aircraftId' : IDL.Text,
  'takeoffTime' : IDL.Text,
  'landingTime' : IDL.Text,
  'landingType' : IDL.Text,
  'landingCount' : IDL.Nat,
});
export const Instructor = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
export const Student = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });

export const idlService = IDL.Service({
  'createAircraft' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createExercise' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'createFlightLog' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'createInstructor' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createStudent' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteAircraft' : IDL.Func([IDL.Text], [], []),
  'deleteExercise' : IDL.Func([IDL.Text], [], []),
  'deleteFlightLog' : IDL.Func([IDL.Nat], [], []),
  'deleteInstructor' : IDL.Func([IDL.Text], [], []),
  'deleteStudent' : IDL.Func([IDL.Text], [], []),
  'exportFlightLogsAsCSV' : IDL.Func([], [IDL.Text], ['query']),
  'getAllAircraft' : IDL.Func([], [IDL.Vec(Aircraft)], ['query']),
  'getAllExercises' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
  'getAllFlightLogs' : IDL.Func([], [IDL.Vec(FlightLog)], ['query']),
  'getAllInstructors' : IDL.Func([], [IDL.Vec(Instructor)], ['query']),
  'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getInstructorReport' : IDL.Func(
      [IDL.Text],
      [IDL.Float64, IDL.Nat],
      ['query'],
    ),
  'getStudentTotalHours' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
  'updateAircraft' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateExercise' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateFlightLog' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateInstructor' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateStudent' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Aircraft = IDL.Record({ 'id' : IDL.Text, 'registration' : IDL.Text });
  const Exercise = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const FlightLog = IDL.Record({
    'id' : IDL.Nat,
    'studentId' : IDL.Text,
    'exerciseId' : IDL.Text,
    'totalHours' : IDL.Float64,
    'date' : IDL.Text,
    'flightType' : IDL.Text,
    'instructorId' : IDL.Text,
    'aircraftId' : IDL.Text,
    'takeoffTime' : IDL.Text,
    'landingTime' : IDL.Text,
    'landingType' : IDL.Text,
    'landingCount' : IDL.Nat,
  });
  const Instructor = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
  const Student = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
  
  return IDL.Service({
    'createAircraft' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createExercise' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'createFlightLog' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'createInstructor' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createStudent' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteAircraft' : IDL.Func([IDL.Text], [], []),
    'deleteExercise' : IDL.Func([IDL.Text], [], []),
    'deleteFlightLog' : IDL.Func([IDL.Nat], [], []),
    'deleteInstructor' : IDL.Func([IDL.Text], [], []),
    'deleteStudent' : IDL.Func([IDL.Text], [], []),
    'exportFlightLogsAsCSV' : IDL.Func([], [IDL.Text], ['query']),
    'getAllAircraft' : IDL.Func([], [IDL.Vec(Aircraft)], ['query']),
    'getAllExercises' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
    'getAllFlightLogs' : IDL.Func([], [IDL.Vec(FlightLog)], ['query']),
    'getAllInstructors' : IDL.Func([], [IDL.Vec(Instructor)], ['query']),
    'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getInstructorReport' : IDL.Func(
        [IDL.Text],
        [IDL.Float64, IDL.Nat],
        ['query'],
      ),
    'getStudentTotalHours' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
    'updateAircraft' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateExercise' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateFlightLog' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateInstructor' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateStudent' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };