/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Aircraft { 'id' : string, 'registration' : string }
export interface Exercise {
  'id' : string,
  'name' : string,
  'description' : string,
}
export interface FlightLog {
  'id' : bigint,
  'studentId' : string,
  'exerciseId' : string,
  'totalHours' : number,
  'date' : string,
  'flightType' : string,
  'instructorId' : string,
  'aircraftId' : string,
  'takeoffTime' : string,
  'landingTime' : string,
  'landingType' : string,
  'landingCount' : bigint,
}
export interface Instructor { 'id' : string, 'name' : string }
export interface Student { 'id' : string, 'name' : string }
export interface _SERVICE {
  'createAircraft' : ActorMethod<[string, string], undefined>,
  'createExercise' : ActorMethod<[string, string, string], undefined>,
  'createFlightLog' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      bigint,
      string,
      string,
    ],
    bigint
  >,
  'createInstructor' : ActorMethod<[string, string], undefined>,
  'createStudent' : ActorMethod<[string, string], undefined>,
  'deleteAircraft' : ActorMethod<[string], undefined>,
  'deleteExercise' : ActorMethod<[string], undefined>,
  'deleteFlightLog' : ActorMethod<[bigint], undefined>,
  'deleteInstructor' : ActorMethod<[string], undefined>,
  'deleteStudent' : ActorMethod<[string], undefined>,
  'exportFlightLogsAsCSV' : ActorMethod<[], string>,
  'getAllAircraft' : ActorMethod<[], Array<Aircraft>>,
  'getAllExercises' : ActorMethod<[], Array<Exercise>>,
  'getAllFlightLogs' : ActorMethod<[], Array<FlightLog>>,
  'getAllInstructors' : ActorMethod<[], Array<Instructor>>,
  'getAllStudents' : ActorMethod<[], Array<Student>>,
  'getInstructorReport' : ActorMethod<[string], [number, bigint]>,
  'getStudentTotalHours' : ActorMethod<[string], number>,
  'updateAircraft' : ActorMethod<[string, string], undefined>,
  'updateExercise' : ActorMethod<[string, string, string], undefined>,
  'updateFlightLog' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      bigint,
      string,
      string,
    ],
    undefined
  >,
  'updateInstructor' : ActorMethod<[string, string], undefined>,
  'updateStudent' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];